### ISSUE TITLE
Error message problem during enrollment when username is taken

### ISSUE THREAD

**Issue by gretchiesprite** [NorthBridge/nexus-community#174]
When enrolling, if the desired username is already taken, the user only finds this out after they've submitted the form and they are taken to a new page with an error message that would likely be confusing to them (see attached photo). Could we change the page so that a message pops up as they are typing to say if the user name is available or not? Or, after they click submit, if the name isn't available, could we keep them on that page with a message saying to select another username?

![screen shot 2015-08-16 at 7 56 54 pm](https://cloud.githubusercontent.com/assets/2071968/9296391/d029a8ae-4451-11e5-96bc-8e573e16ae3a.png)

**Comment by kdflint** [comment]
This is fixed in a less than perfect way.

The complication is that most validations are running client side (in the browser prior to the submit actually occurring). This validation happens server side AFTER the form has been submitted.

For now this case will now return to the enrollment screen and show an informational message. All the user entries are blanked though. Not so great.

I have opened a new issues to improve user feedback on legitimate server-side validation fails like this one. (#178)

fyi - Most of the server side validations will not be kind to the user as they could only have happened nefariously. That is, if the form passed the front validation it will only fail server validation if someone intercepted and manipulated the POST. But there are a few exceptions like this one. So I need to design a better solution with #178,

**Comment by gretchiesprite** [comment]
In Safari and Chrome, I'm still getting the same message as when I opened the issue. Also, for email, I'm able to enter a different email than the one that the enrollment package was sent to. Do we want to check and make sure those emails match, or maybe ask the user to double check their email?

**Comment by kdflint** [comment]
Oops - I did not transfer tie fix to the server. Should be good now...?

On the enrollment email question.. I have debated this... I decided to give the enrollee flexibility to select a different email address than the one the administrator designated because we have the safeguard in place that an invitation can only be used once. Also, the user's email address surfaces on the UI so it will be reasonably clear if someone stole it and then they are easily deleted.

That 32-digit invitation id is not easily guessable and if someone actually stole the email itself the address would be on the email envelope anyway. And finally the invitation expires after one month. (which we could shorten if we want - wasn't sure what to set that to)

Thoughts? Is this wise?

**Comment by kcavness** [comment]
I agree with Kathy that offering the user a chance to enter a different email address than the original is a good idea; I often wish for the same functionality in other circumstances (especially stuff I got signed up for at work!). I also don't think the security considerations are too high a priority in this case.

**Comment by gretchiesprite** [comment]
The correct error message is showing now. Closing.
